services:
  - type: web
    name: kenya-climate-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: db.bkayhzqohdxvhurzigjg.supabase.co
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000